version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:10.3'
    environment:
      - MARIADB_USER=bn_reportserver
      - MARIADB_DATABASE=bitnami_reportserver
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  reportserverenterprise:
    image: 'bitnami/reportserverenterprise:3'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - REPORTSERVER_DATABASE_USER=bn_reportserver
      - REPORTSERVER_DATABASE_NAME=bitnami_reportserver
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '80:8080'
      - '443:8443'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
